version: 2.1 #circleCI version

orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  deploy:
    docker:
      - image: cimg/openjdk:17.0.9
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - docker/pull:
          images: georgiealx/education-space:v1.0.1
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a devopsproj
            heroku container:release web -a devopsproj

workflows:
  simple_workflow:
    jobs:
      - deploy
